[repositories.NI-Switch-Relay-Custom-Device]
release_branches = [ "master",]
build_number = 3

[repositories.Instrument-Custom-Device]
release_branches = [ "feature/integration-tests",]
build_number = 4

[repositories.Waveform-Processing-Custom-Device]
build_number = 0

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 13

[repositories.commonbuild-configuration]

[repositories.Chassis-TimeSync-Custom-Device]
release_branches = [ "master", "develop",]
build_number = 31
