[repositories.Instrument-Custom-Device]
build_number = 7

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 6

[repositories.commonbuild-configuration]

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 14
