[repositories.Instrument-Custom-Device]
build_number = 8

[repositories.NI-Switch-Relay-Custom-Device]
build_number = 0

[repositories.BCI-SLSC-LOAD]
build_number = 1

[repositories.BCI-SLSC-VDT]
build_number = 5

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 21

[repositories.commonbuild-configuration]

[repositories.VeriStand-steps-for-TestStand]
build_number = 0

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 15
