[repositories.BCI-SLSC-LOAD]
build_number = 1

[repositories.BCI-SLSC-VDT]
build_number = 3

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 12

[repositories.commonbuild-configuration]

[repositories.Data-Publishing-Service]
build_number = 4
