[repositories.BCI-SLSC-VDT]
build_number = 0

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 7

[repositories.commonbuild-configuration]

[repositories.Data-Publishing-Service]
build_number = 4
