[repositories.Instrument-Custom-Device]
build_number = 7

[repositories.NI-Switch-Relay-Custom-Device]
build_number = 0

[repositories.BCI-SLSC-VDT]
build_number = 1

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 10

[repositories.commonbuild-configuration]

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 15
