[repositories.NI-Switch-Relay-Custom-Device]
release_branches = [ "master",]
build_number = 3

[repositories.Instrument-Custom-Device]
release_branches = [ "feature/integration-tests",]
build_number = 4

[repositories.BCI-SLSC-LOAD]
build_number = 1

[repositories.BCI-SLSC-VDT]
build_number = 3

[repositories.Waveform-Processing-Custom-Device]
build_number = 2

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 24

[repositories.commonbuild-configuration]

[repositories.VeriStand-steps-for-TestStand]
build_number = 1

[repositories.Chassis-TimeSync-Custom-Device]
release_branches = [ "master", "develop",]
build_number = 31
