[repositories.Instrument-Custom-Device]
build_number = 7

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 3

[repositories.commonbuild-configuration]

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 14
